# Generated by Django 5.0.6 on 2024-06-18 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khanadotcom_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
