# Generated by Django 5.0.6 on 2024-06-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khanadotcom_app', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
