# Generated by Django 5.0.6 on 2024-06-18 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khanadotcom_app', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customerdetails',
            table='customer_info',
        ),
    ]
