# Generated by Django 5.0.6 on 2024-06-18 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khanadotcom_app', '0004_alter_customerdetails_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customerdetails',
            table='customer_details',
        ),
    ]
