# Generated by Django 5.0.6 on 2024-06-18 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khanadotcom_app', '0005_alter_customerdetails_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerdetails',
            options={'managed': True, 'verbose_name': 'Customer Details'},
        ),
    ]
