# Generated by Django 5.0.6 on 2024-06-18 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khanadotcom_app', '0006_alter_customerdetails_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerDetails',
            new_name='CustomerDetail',
        ),
        migrations.AlterModelOptions(
            name='customerdetail',
            options={'managed': True},
        ),
    ]
