# Generated by Django 5.0.6 on 2024-06-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khanadotcom_app', '0007_rename_customerdetails_customerdetail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='image_url',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='menu_item_pic',
            field=models.ImageField(blank=True, null=True, upload_to='menu_items/'),
        ),
    ]
